![car](car.jpg)

Insurance companies invest a lot of [time and money](https://www.accenture.com/_acnmedia/pdf-84/accenture-machine-leaning-insurance.pdf) into optimizing their pricing and accurately estimating the likelihood that customers will make a claim. In many countries insurance it is a legal requirement to have car insurance in order to drive a vehicle on public roads, so the market is very large!

Knowing all of this, On the Road car insurance have requested your services in building a model to predict whether a customer will make a claim on their insurance during the policy period. As they have very little expertise and infrastructure for deploying and monitoring machine learning models, they've asked you to identify the single feature that results in the best performing model, as measured by accuracy, so they can start with a simple model in production.

They have supplied you with their customer data as a csv file called `car_insurance.csv`, along with a table detailing the column names and descriptions below.



## The dataset

| Column | Description |
|--------|-------------|
| `id` | Unique client identifier |
| `age` | Client's age: <br> <ul><li>`0`: 16-25</li><li>`1`: 26-39</li><li>`2`: 40-64</li><li>`3`: 65+</li></ul> |
| `gender` | Client's gender: <br> <ul><li>`0`: Female</li><li>`1`: Male</li></ul> |
| `driving_experience` | Years the client has been driving: <br> <ul><li>`0`: 0-9</li><li>`1`: 10-19</li><li>`2`: 20-29</li><li>`3`: 30+</li></ul> |
| `education` | Client's level of education: <br> <ul><li>`0`: No education</li><li>`1`: High school</li><li>`2`: University</li></ul> |
| `income` | Client's income level: <br> <ul><li>`0`: Poverty</li><li>`1`: Working class</li><li>`2`: Middle class</li><li>`3`: Upper class</li></ul> |
| `credit_score` | Client's credit score (between zero and one) |
| `vehicle_ownership` | Client's vehicle ownership status: <br><ul><li>`0`: Does not own their vehilce (paying off finance)</li><li>`1`: Owns their vehicle</li></ul> |
| `vehcile_year` | Year of vehicle registration: <br><ul><li>`0`: Before 2015</li><li>`1`: 2015 or later</li></ul> |
| `married` | Client's marital status: <br><ul><li>`0`: Not married</li><li>`1`: Married</li></ul> |
| `children` | Client's number of children |
| `postal_code` | Client's postal code | 
| `annual_mileage` | Number of miles driven by the client each year |
| `vehicle_type` | Type of car: <br> <ul><li>`0`: Sedan</li><li>`1`: Sports car</li></ul> |
| `speeding_violations` | Total number of speeding violations received by the client | 
| `duis` | Number of times the client has been caught driving under the influence of alcohol |
| `past_accidents` | Total number of previous accidents the client has been involved in |
| `outcome` | Whether the client made a claim on their car insurance (response variable): <br><ul><li>`0`: No claim</li><li>`1`: Made a claim</li></ul> |

# **Project Instructions**

* Identify the single feature of the data that is the best predictor of whether a customer will put in a claim (the `"outcome"` column), excluding the `"id"` column.

* Store as a DataFrame called `best_feature_df`, containing columns named `"best_feature"` and `"best_accuracy"` with the name of the feature with the highest accuracy, and the respective accuracy score.

In [9]:
# Import required modules
import pandas as pd
import numpy as np
from statsmodels.formula.api import logit

df = pd.read_csv('car_insurance.csv')
df = df.dropna()
df['age'] = df['age'].replace({0: '16-25', 1: '26-39', 2: '40-64', 3: '65+'})
df['gender'] = df['gender'].replace({0: 'Female', 1: 'Male'})
df['driving_experience'] = df['driving_experience'].replace({0: '0-9', 1: '10-19', 2: '20-29', 3: '30+'})
df['vehicle_ownership'] = df['vehicle_ownership'].replace({0.0: 'Does not own their vehilce', 1.0: 'Owns their vehicle'})
df['married'] = df['married'].replace({0.0:'Not married', 1.0: 'Married'})
df['postal_code'] = df['postal_code'].astype(str)

df.head()

       id    age  gender  ... duis past_accidents outcome
0  569520    65+  Female  ...    0              0     0.0
1  750365  16-25    Male  ...    0              0     1.0
2  199901  16-25  Female  ...    0              0     0.0
3  478866  16-25    Male  ...    0              0     0.0
4  731664  26-39    Male  ...    0              1     1.0

[5 rows x 18 columns]

In [10]:
temp = 'outcome ~ '
d = dict()
for i in df.columns.to_list()[1:-1]:
    formula = temp + i
    model = logit(formula, data=df).fit()
    con = model.pred_table()
    accuracy = (con[1, 1] + con[0, 0])/ (con[1, 1] + con[0, 0] + con[0, 1] + con[1, 0])
    print(i)
    d[i] = accuracy
d

Optimization terminated successfully.
         Current function value: 0.507371
         Iterations 6
age
Optimization terminated successfully.
         Current function value: 0.615189
         Iterations 5
gender
Optimization terminated successfully.
         Current function value: 0.466479
         Iterations 8
driving_experience
Optimization terminated successfully.
         Current function value: 0.603304
         Iterations 5
education
Optimization terminated successfully.
         Current function value: 0.533082
         Iterations 6
income
Optimization terminated successfully.
         Current function value: 0.566906
         Iterations 6
credit_score
Optimization terminated successfully.
         Current function value: 0.548159
         Iterations 5
vehicle_ownership
Optimization terminated successfully.
         Current function value: 0.572577
         Iterations 6
vehicle_year
Optimization terminated successfully.
         Current function value: 0.587413
         Iterations 5
married
Optimization terminated successfully.
         Current function value: 0.594367
         Iterations 5
children
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.599148
         Iterations: 35
postal_code
Optimization terminated successfully.
         Current function value: 0.602726
         Iterations 5
annual_mileage

/usr/local/lib/python3.8/dist-packages/statsmodels/base/model.py:607: ConvergenceWarning:

Maximum Likelihood optimization failed to converge. Check mle_retvals

Optimization terminated successfully.
         Current function value: 0.620057
         Iterations 5
vehicle_type
Optimization terminated successfully.
         Current function value: 0.556681
         Iterations 7
speeding_violations
Optimization terminated successfully.
         Current function value: 0.596760
         Iterations 6
duis
Optimization terminated successfully.
         Current function value: 0.546366
         Iterations 7
past_accidents

{'age': 0.7740827095349122,
 'gender': 0.6887961713093631,
 'driving_experience': 0.7781322861700822,
 'education': 0.6887961713093631,
 'income': 0.7399680942446926,
 'credit_score': 0.706589765615413,
 'vehicle_ownership': 0.7392318075837526,
 'vehicle_year': 0.6887961713093631,
 'married': 0.6887961713093631,
 'children': 0.6887961713093631,
 'postal_code': 0.7013130445453429,
 'annual_mileage': 0.692723033501043,
 'vehicle_type': 0.6887961713093631,
 'speeding_violations': 0.6887961713093631,
 'duis': 0.6887961713093631,
 'past_accidents': 0.6887961713093631}

In [6]:
best_feature_df = pd.DataFrame(data={'best_feature':['driving_experience'], 'best_accuracy':[0.7781322861700822]})
best_feature_df

         best_feature  best_accuracy
0  driving_experience       0.778132